package lewandowski.electronic_gradebook.model.enums;

import lombok.Getter;

@Getter
public enum Country {
    AFGHANISTAN ("AF", "Afganistan"),
    ALAND_ISLANDS ("AX", "Wyspy Alandzkie"),
    ALBANIA ("AL", "Albania"),
    ALGERIA ("DZ","Algieria"),
    AMERICAN_SAMOA ("AS","Samoa Amerykańskie"),
    ANDORRA ("AD","Andora"),
    ANGOLA ("AO","Angola"),
    ANGUILLA ("AI","Anguilla"),
    ANTARCTICA ("AQ","Antarktyda"),
    ANTIGUA_AND_BARBUDA ("AG","Antigua i Barbuda"),
    ARGENTINA ("AR","Argentyna"),
    ARMENIA ("AM","Armenia"),
    ARUBA ("AW","Aruba"),
    AUSTRALIA ("AU","Australia"),
    AUSTRIA ("AT","Austria"),
    AZERBAIJAN ("AZ","Azerbejdżan"),
    BAHAMAS ("BS","Bahamy"),
    BAHRAIN ("BH","Bahrajn"),
    BANGLADESH ("BD","Bangladesz"),
    BARBADOS ("BB","Barbados" ),
    BELARUS ("BY","Białoruś" ),
    BELGIUM ("BE","Belgia" ),
    BELIZE ("BZ","Belize" ),
    BENIN ("BJ","Benin" ),
    BERMUDA ("BM","Bermudy" ),
    BHUTAN ("BT","Bhutan" ),
    BOLIVIA ("BO","Boliwia" ),
    BOSNIA_AND_HERZEGOVINA ("BA","Bośnia i Hercegowina"),
    BOTSWANA ("BW","Botswana" ),
    BRAZIL ("BR","Brazylia" ),
    BRITISH_INDIAN_OCEAN_TERRITORY ("IO","Brytyjskie Terytorium Oceanu Indyjskiego" ),
    BRUNEI ("BN","Brunei" ),
    BULGARIA ("BG","Bułgaria" ),
    BURKINA_FASO ("BF","Burkina Faso"),
    BURUNDI ("BI","Burundi" ),
    CAMBODIA ("KH","Kambodża" ),
    CAMEROON ("CM","Kamerun" ),
    CANADA ("CA","Kanada" ),
    CAPE_VERDE ("CV","Wyspy Zielonego Przylądka"),
    CAYMAN_ISLANDS ("KY","Kajmany" ),
    CENTRAL_AFRICAN_REPUBLIC ("CF","Republika Środkowoafrykańska"),
    CHAD ("TD","Czad" ),
    CHILE ("CL","Chile" ),
    CHINA ("CN","Chiny" ),
    COLOMBIA ("CO","Kolumbia" ),
    COMOROS ("KM","Komory" ),
    CONGO ("CG","Kongo" ),
    COOK_ISLANDS ("CK","Wyspy Cooka"),
    COSTA_RICA ("CR","Kostaryka" ),
    CROATIA ("HR","Chorwacja"),
    CUBA ("CU","Kuba" ),
    CYPRUS ("CY","Cypr" ),
    CZECH_REPUBLIC ("CZ","Czechy"),
    DENMARK ("DK","Dania" ),
    DJIBOUTI ("DJ","Dżibuti"),
    DOMINICA ("DM","Dominika" ),
    DOMINICAN_REPUBLIC ("DO","Dominikana" ),
    ECUADOR ("EC","Ekwador" ),
    EGYPT ("EG","Egipt" ),
    ERITREA ("ER","Erytrea" ),
    ESTONIA ("EE","Estonia" ),
    ETHIOPIA ("ET","Etiopia" ),
    FIJI ("FJ","Fidżi" ),
    FINLAND ("FI","Finlandia" ),
    FRANCE ("FR","Francja" ),
    GABON ("GA","Gabon" ),
    GAMBIA ("GM","Gambia" ),
    GEORGIA ("GE","Gruzja" ),
    GERMANY ("DE","Niemcy" ),
    GHANA ("GH","Ghana" ),
    GIBRALTAR ("GI","Gibraltar" ),
    GREECE ("GR","Grecja" ),
    GREENLAND ("GL","Grenlandia" ),
    GRENADA ("GD","Grenada" ),
    GUADELOUPE ("GP","Gwadelupa" ),
    GUAM ("GU","Guam" ),
    GUATEMALA ("GT","Gwatemala" ),
    GUERNSEY ("GG","Guernsey" ),
    GUINEA ("GN,","Gwinea" ),
    GUINEA_BISSAU ("GW","Gwinea Bissau"),
    GUYANA ("GY","Gujana" ),
    HAITI ("HT","Haiti" ),
    HONDURAS ("HN","Honduras" ),
    HONG_KONG ("HK","Hongkong" ),
    HUNGARY ("HU","Węgry" ),
    ICELAND ("IS","Islandia" ),
    INDIA ("IN","Indie" ),
    INDONESIA ("ID","Indonezja" ),
    IRAN ("IR","Iran" ),
    IRAQ ("IQ","Irak" ),
    IRELAND ("IE","Irlandia" ),
    ISLE_OF_MAN ("IM","Wyspa Man"),
    ISRAEL ("IL","Izrael" ),
    ITALY ("IT","Włochy" ),
    JAMAICA ("JM","Jamajka" ),
    JAPAN ("JP","Japonia" ),
    JERSEY ("JE","Jersey" ),
    JORDAN ("JO","Jordania" ),
    KAZAKHSTAN ("KZ","Kazachstan" ),
    KENYA ("KE","Kenia" ),
    KIRIBATI ("KI","Kiribati" ),
    KOREA ("KR","Korea"),
    KUWAIT ("KW","Kuwejt" ),
    KYRGYZSTAN ("KG","Kirgistan" ),
    LATVIA ("LV","Łotwa" ),
    LEBANON ("LB","Liban" ),
    LESOTHO ("LS","Lesotho" ),
    LIBERIA ("LR","Liberia" ),
    LIECHTENSTEIN ("LI","Liechtenstein" ),
    LITHUANIA ("LT","Litwa" ),
    LUXEMBOURG ("LU","Luksemburg" ),
    MACAO ("MO","Makao" ),
    MACEDONIA ("MK","Macedonia"),
    MADAGASCAR ("MG","Madagaskar" ),
    MALAWI ("MW","Malawi" ),
    MALAYSIA ("MY","Malezja" ),
    MALDIVES ("MV","Malediwy" ),
    MALI ("ML","Mali" ),
    MALTA ("MT","Malta" ),
    MARSHALL_ISLANDS ("MH","Wyspy Marshalla"),
    MARTINIQUE ("MQ","Martynika" ),
    MAURITANIA ("MR","Mauretania" ),
    MAURITIUS ("MU","Mauritius" ),
    MAYOTTE ("YT","Majotta" ),
    MEXICO ("MX","Meksyk" ),
    MICRONESIA ("FM","Mikronezja" ),
    MOLDOVA ("MD","Mołdawia" ),
    MONACO ("MC","Monako" ),
    MONGOLIA ("MN","Mongolia" ),
    MONTENEGRO ("ME","Czarnogóra" ),
    MONTSERRAT ("MS","Montserrat" ),
    MOROCCO ("MA","Maroko" ),
    MOZAMBIQUE ("MZ","Mozambik" ),
    MYANMAR ("MM","Myanmar" ),
    NAMIBIA ("NA","Namibia" ),
    NAURU ("NR","Nauru" ),
    NEPAL ("NP","Nepal" ),
    NETHERLANDS ("NL","Holandia" ),
    NEW_CALEDONIA ("NC","Nowa Kaledonia"),
    NEW_ZEALAND ("NZ","Nowa Zelandia"),
    NICARAGUA ("NI","Nikaragua" ),
    NIGER ("NE","Niger" ),
    NIGERIA ("NG","Nigeria" ),
    NIUE ("NU","Niue" ),
    NORWAY ("NO","Norwegia"),
    OMAN ("OM","Oman" ),
    PAKISTAN ("PK","Pakistan" ),
    PALAU ("PW","Palau" ),
    PANAMA ("PA","Panama" ),
    PAPUA_NEW_GUINEA ("PG","Papua Nowa Gwinea"),
    PARAGUAY ("PY","Paragwaj" ),
    PERU ("PE","Peru" ),
    PHILIPPINES ("PH","Filipiny" ),
    PITCAIRN ("PN","Wyspy Pitcairn"),
    POLAND ("PL","Polska" ),
    PORTUGAL ("PT","Portugalia" ),
    PUERTO_RICO ("PR","Pseudoakcenty" ),
    QATAR ("QA","Katar" ),
    REUNION ("RE","Reunion" ),
    ROMANIA ("RO","Rumunia" ),
    RUSSIAN_FEDERATION ("RU","Rosja" ),
    RWANDA ("RW","Rwanda" ),
    SAMOA ("WS","Samoa" ),
    SAN_MARINO ("SM","San Marino"),
    SAUDI_ARABIA ("SA","Arabia Saudyjska"),
    SENEGAL ("SN","Senegal" ),
    SERBIA ("RS","Serbia" ),
    SEYCHELLES ("SC","Seszele" ),
    SIERRA_LEONE ("SL","Sierra Leone"),
    SINGAPORE ("SG","Singapur" ),
    SLOVAKIA ("SK","Słowacja" ),
    SLOVENIA ("SI","Słowacja" ),
    SOLOMON_ISLANDS ("SB","Wyspy Salomona"),
    SOMALIA ("SO","Somalia" ),
    SOUTH_AFRICA ("ZA","Republika Południowej Afryki"),
    SPAIN ("ES","Hiszpania" ),
    SRILANKA ("LK","Sri Lanka"),
    SUDAN ("SD","Sudan" ),
    SURINAME ("SR","Surinam" ),
    SWEDEN ("SE","Szwecja" ),
    SWITZERLAND ("CH","Szwajcaria" ),
    SYRIAN_ARAB_REPUBLIC ("SY","Syria"),
    TAIWAN ("TW","Tajwan" ),
    TAJIKISTAN ("TJ","Tadżykistan" ),
    TANZANIA ("TZ","Tanzania" ),
    THAILAND ("TH","Tajlandia" ),
    TOGO ("TG","Togo" ),
    TOKELAU ("TK","Tokelau" ),
    TONGA ("TO","Tonga" ),
    TRINIDAD_AND_TOBAGO ("TT","Trynidad i Tobago"),
    TUNISIA ("TN","Tunezja" ),
    TURKEY ("TR","Turcja" ),
    TURKMENISTAN ("TM","Turkmenistan" ),
    TUVALU ("TV","Tuvalu" ),
    UGANDA ("UG","Uganda" ),
    UKRAINE ("UA","Ukraina" ),
    UNITED_ARAB_EMIRATES ("AE","Zjednoczone Emiraty Arabskie"),
    UNITED_KINGDOM ("GB","Wielka Brytania"),
    UNITED_STATES ("US","Stany Zjednoczone"),
    URUGUAY ("UY","Urugwaj" ),
    UZBEKISTAN ("UZ","Uzbekistan" ),
    VANUATU ("VU","Vanuatu" ),
    VENEZUELA ("VE","Wenezuela" ),
    VIETNAM ("VN","Wietnam" ),
    YEMEN ("YE","Jemen" ),
    ZAMBIA ("ZM","Zambia" ),
    ZIMBABWE ("ZW","Zimbabwe" );

    private String code;
    private String polishNameCountry;

    Country(String code, String polishNameCountry) {
        this.code = code;
        this.polishNameCountry = polishNameCountry;
    }
}
